---
# tasks file for mongodb
- name: mongodb | Repositories updated
  yum_repository:
    name: "{{ mongodb_package_name }}"
    description: "MongoDB Repository"
    baseurl: "{{ mongodb_redhat_repo }}"
    gpgkey: "{{ mongodb_redhat_key }}"
    gpgcheck: yes
    enabled: yes

- name: mongodb | MongoDB installed
  yum:
    name: "{{ mongodb_package_name }}"
    state: present
  register: mongodb_package_installed

- name: mongodb | Start service MongoDB
  service:
    name: "{{ mongodb_service_name }}"
    state: started
    enabled: yes
  when: mongodb_package_installed.changed

- name: mongodb | MongoDB configured
  template:
    src: "{{ mongodb_template_path }}/mongodb.conf.j2"
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify: restart "{{ mongodb_service_name }}"
